### ISSUE TITLE
Add NPR Badging Comment Experiment

### ISSUE THREAD

**Issue by melodykramer** [lisawilliams/doreadthecomments#1]
[What Happens When You Allow Badging in Comments](http://socialmediadesk.tumblr.com/post/101670504116/what-happens-when-you-allow-badging-in-comments) - 1. create affiliate communities within the larger comment section.
1. improve the commenting experience. Though people would still be anonymous, they would be revealing something about themselves through an affiliation, which would lead to better comments.
2. lead to communities that might head off line (to events, etc.)
3. lessen the hostility seen in most comment sections.
4. connect stations with members and potential members

**Comment by lisawilliams** [comment]
Thank you, Melody!  I have integrated these: https://github.com/lisawilliams/doreadthecomments/commit/8466e5fb126a1c9403dc24e61c2fa21920369789
